version: '3'
services:
  php:
    build:
      context: ./
    volumes:
      - ./php:/var/www
      - composer_cache:/home/docker/.composer/cache
    working_dir: /var/www
    links:
      - mysql
  web:
    image: nginx:1.10
    volumes:
      - ./php:/var/www
    links:
      - php
  mysql:
    image: mysql:5.7
  node:
    image: node:10
    volumes:
      - ./php:/var/www
    working_dir: /var/www
    user: node
    command: bash -c 'yarn && yarn run watch'
  socket:
    build: ./docker/socket
    working_dir: "/usr/src/app"
volumes:
  composer_cache:
